travis:
  secure:
    BINSTAR_TOKEN: RtWZmI/Pq88s/QdsHo5+HMqD3t9QveHnvzbpff/UxWHdtLG2b3WvoRX1f5/YSRqROnh/rGUZmcMw3FV5XczyoYigH9o8dESD/oihi2uCpT+eX/qfdqjH02ZgFGOAEgHIcpiA1mtxztIkBRGjAMnvTogFsQpXcq5CtwEbw5XRzdKJqstGON85zS+BR+lgcsjr9H4DHHeMDoWroon38SLbT1c77kVZ+QmUM1tGxRJK1n/tgQXz5DIWLCv0sEEqZHpBayPPAozn3uKKWNbavGZz796voMavh6ve9z/doK9FOL6mATgVBbfQntgMLF7QExc2RLTneB4IZbiGpDJnc1oJsRfyeiee+EdN5RyhLIUZbmXkhcvnur85ZeTEDEo/tGQrHQbsTidIdqyZHkhgsX89GLZUp79h4+OjnbRATtA5/9L4wj4mHgRFwSGt6+2YkaT5FTitM8icP3VjZo3tNLpCbyTrwi6NP4foakWGnxPTaV7tNIpk2ZWteIyxN67Ewb7XCb+UwvAYYoNJWjKVHDujaFIIlglElW/X8bLO7ny5IifbclEP4EIah5bcchPhh2GzWYi8fPYqnrxslOgaiVb7FEP25SAgIAVjQ3qnFdp6AUGeNP/anqd8c+N8L9HYm+q4jyq07cNVPll38m2xTYOcngj6ozGk7M1DesjSm9Te9/M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
